[tools]
bat = "latest"
bottom = "latest"
caddy = "latest"
delta = "latest"
doggo = "latest"
dust = "latest"
e1s = "latest"
eza = "latest"
fd = "latest"
gcloud = "latest"
gh = "latest"
go = "latest"
jq = "latest"
k6 = "latest"
lazygit = "latest"
marp-cli = "latest"
"aqua:neovim/neovim" = "latest"
node = "25"
"npm:@googleworkspace/cli" = "latest"
prek = "latest"
"github:dalance/procs" = "latest"
python = "latest"
ripgrep = "latest"
"github:grafana/mcp-grafana" = "latest"
uv = "latest"
xh = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
