[tools]
bat = "latest"
caddy = "latest"
delta = "latest"
e1s = "latest"
gcloud = "latest"
gh = "latest"
go = "latest"
k6 = "latest"
marp-cli = "latest"
neovim = "stable"
node = "25"
"npm:@googleworkspace/cli" = "latest"
prek = "latest"
python = "latest"
"github:grafana/mcp-grafana" = "latest"
uv = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
